[QOLDEV-313] sync tests with other repos
- Reduce unnecessary test data
- Standardise test dataset creation
- Clean up 'when' vs 'then' in Behave steps

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -19,6 +19,7 @@ commands:
   build-network:
     usage: Ensure that the amazeeio network exists.
     cmd: |
+      ahoy title "Creating amazeeio Docker network"
       docker network prune -f > /dev/null
       docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network
 
@@ -34,13 +35,14 @@ commands:
   up:
     usage: Build and start Docker containers.
     cmd: |
+      ahoy title "Building and starting Docker containers"
       docker-compose up -d "$@"
+      echo "Initialising database schema"
       ahoy cli '$APP_DIR/bin/init.sh'
-      sleep 10
-      docker-compose logs
+      echo "Waiting for containers to start listening..."
       ahoy cli "dockerize -wait tcp://ckan:5000 -timeout 1m"
-      if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi
-      if docker-compose logs | grep -q "Exception"; then docker-compose logs; exit 1; fi
+      if docker-compose logs | grep -q "\[Error\]"; then exit 1; fi
+      if docker-compose logs | grep -q "Exception"; then exit 1; fi
       docker ps -a --filter name=^/${COMPOSE_PROJECT_NAME}_
       export DOCTOR_CHECK_CLI=0
 
@@ -66,7 +68,7 @@ commands:
 
   pull:
     usage: Pull latest docker images.
-    cmd: if [ ! -z "$(docker image ls -q)" ]; then docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep amazeeio/ | grep -v none | xargs -n1 docker pull | cat; fi
+    cmd: if [ ! -z "$(docker image ls -q)" ]; then docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep ckan/ckan- | grep -v none | xargs -n1 docker pull | cat; fi
 
   cli:
     usage: Start a shell inside CLI container or run a command.
@@ -78,11 +80,14 @@ commands:
 
   install-site:
     usage: Install test site data.
-    cmd: ahoy cli '$APP_DIR/bin/create-test-data.sh'
+    cmd: |
+      ahoy title "Installing a fresh site"
+      ahoy cli '$APP_DIR/bin/init.sh && $APP_DIR/bin/create-test-data.sh'
 
   clean:
     usage: Remove containers and all build files.
     cmd: |
+      ahoy title "Cleaning up old builds"
       ahoy down
       # Remove other directories.
       # @todo: Add destinations below.
@@ -104,6 +109,7 @@ commands:
   lint:
     usage: Lint code.
     cmd: |
+      ahoy title 'Check for lint'
       ahoy cli "flake8 ${@:-ckanext}" || \
       [ "${ALLOW_LINT_FAIL:-0}" -eq 1 ]
 
@@ -112,7 +118,7 @@ commands:
     cmd: |
       docker cp . $(docker-compose ps -q ckan):/srv/app/
       docker cp bin/ckan_cli $(docker-compose ps -q ckan):/usr/bin/
-      ahoy cli 'chmod -v u+x /usr/bin/ckan_cli; cp -v .docker/test.ini $CKAN_INI'
+      ahoy cli 'chmod -v u+x /usr/bin/ckan_cli $APP_DIR/bin/*; cp -v .docker/test.ini $CKAN_INI; $APP_DIR/bin/process-config.sh'
 
   pip-list:
     usage: List pip install version details
@@ -125,17 +131,20 @@ commands:
       ahoy lint
       ahoy test-unit
       ahoy install-site
-      ahoy test-bdd || (ahoy logs; exit 1)
+      ahoy test-bdd
 
   test-unit:
     usage: Run unit tests.
     cmd: |
+      ahoy title 'Run unit tests'
       ahoy cli 'pytest --ckan-ini=${CKAN_INI} $APP_DIR/ckanext' || \
       [ "${ALLOW_UNIT_FAIL:-0}" -eq 1 ]
 
   test-bdd:
     usage: Run BDD tests.
     cmd: |
+      ahoy title 'Run scenario tests'
+      ahoy cli "rm -f test/screenshots/*"
       ahoy start-mailmock &
       sleep 5 &&
       ahoy cli "behave -k ${*:-test/features}" --tags=smoke $BEHAVE_TAGS && \
